import { Inter } from "next/font/google";
import { AuthProvider } from "./Provider";
import "../pages/style.css";
import "bootstrap/dist/css/bootstrap.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "KLF LOAD BOARD",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.ico',
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}

