import "./style.css";
import { SessionProvider } from "next-auth/react";
import "bootstrap/dist/css/bootstrap.css";
import Head from "next/head";
import Header from "../components/Header";
import { ChakraProvider } from "@chakra-ui/react";

export default function App({
    Component,
    pageProps: { session, ...pageProps },
}) {
    return (
        <>
            <Head>
                <title>KLF LOAD BOARD</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo2.png" />
            </Head>
            <ChakraProvider>
                <SessionProvider session={session}>
                    <Header />
                    <Component {...pageProps} />
                </SessionProvider>
            </ChakraProvider>
        </>
    );
}
